/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;
import donpos.ABMDonaciones;
import donpos.ObjetosTablas.Donacion;
import donpos.ObjetosTablas.Donante;
/**
 *
 * @author notebook cps
 */
public class VentanaAltasDonacDD extends javax.swing.JFrame {
    
    Donante don = new Donante();
    Donacion donac = new Donacion();
    ABMDonaciones abmdonac = new ABMDonaciones();
    /**
     * Creates new form VentanaAltasDonacDD
     */
    public VentanaAltasDonacDD(Donante don) {
        this.don = don;
        initComponents();
        jLabelDNI.setText(Integer.toString(don.getnDoc()));
        jLabelDNI.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelND = new javax.swing.JLabel();
        jLabelFe = new javax.swing.JLabel();
        jLabelSero = new javax.swing.JLabel();
        jLabelDif = new javax.swing.JLabel();
        jTextFieldND = new javax.swing.JTextField();
        jTextFieldFe = new javax.swing.JTextField();
        jTextFieldSe = new javax.swing.JTextField();
        jTextFieldDif = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jLabelDNI = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelND.setText("Numero de Donación");

        jLabelFe.setText("Fecha");

        jLabelSero.setText("Serología");

        jLabelDif.setText("Diferido");

        jButtonGuardar.setText("Guardar Donación");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabelDNI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("DNI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGuardar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelND)
                            .addComponent(jLabelFe)
                            .addComponent(jLabelSero)
                            .addComponent(jLabelDif)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldND)
                                .addComponent(jTextFieldFe)
                                .addComponent(jTextFieldSe)
                                .addComponent(jTextFieldDif, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelDNI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelND)
                    .addComponent(jTextFieldND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFe)
                    .addComponent(jTextFieldFe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSero)
                    .addComponent(jTextFieldSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDif)
                    .addComponent(jTextFieldDif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGuardar)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        donac.setNumDoc(don.getnDoc());
        donac.setNumDon(Integer.parseInt(jTextFieldND.getText()));
        donac.setFechaDon(jTextFieldFe.getText());
        donac.setSero(jTextFieldSe.getText());
        donac.setDif(jTextFieldDif.getText());
        //Invoca al metodo registrar de la clase ABMDonacion.    
            abmdonac.registrarDonacion(donac);   
            jTextFieldND.setText("");
            jTextFieldFe.setText("");
            jTextFieldSe.setText("");
            jTextFieldDif.setText("");
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelDif;
    private javax.swing.JLabel jLabelFe;
    private javax.swing.JLabel jLabelND;
    private javax.swing.JLabel jLabelSero;
    private javax.swing.JTextField jTextFieldDif;
    private javax.swing.JTextField jTextFieldFe;
    private javax.swing.JTextField jTextFieldND;
    private javax.swing.JTextField jTextFieldSe;
    // End of variables declaration//GEN-END:variables
}
